### ISSUE TITLE
Automate Adding Games

### ISSUE THREAD

**Issue by kanjieater** [Nonary/PlayNiteWatcher#10]
I'd like to request that like your other very useful scripts this would just run automatically in the order of the scripts as specified by the settings.json, to automatically import things that have been exported from PlayNite. Ideally I'd like to just automatically have all playnite entries show up in moonlight, but at least with automating the import it would save one less step anytime there's a game that you want a shortcut for.

**Comment by Nonary** [comment]
Not likely to happen because Sunshine only loads the applications once in the lifetime of the process, it has to be restarted in order to refresh it. Sunshine will need to support hot loading the configuration before this can be done.
