### ISSUE TITLE
Kill game process after end stream like geforce

### ISSUE THREAD

**Issue by AlexAnorak** [Nonary/PlayNiteWatcher#13]
I really miss this function on geforce, so I don’t need to return to game title to end game, just end stream on moonlight 
Is this possible on sunshine?

**Comment by Nonary** [comment]
Yes, that is what this script does. If you terminate the session using moonlight it will force close the running game, provided you have launched it using playnite

**Comment by AlexAnorak** [comment]
Oh, sorry for bother. I just read the md when post, I just tried and it works perfectly! I used to sticking on GFE because of this feature, thank you for your script!
