### ISSUE TITLE
Continues Streaming after Diablo IV exit (battle.net game) exists

### ISSUE THREAD

**Issue by jdkang** [Nonary/PlayNiteWatcher#14]
Not sure if this is a bug or something unavoidable since I believe it's impossible to run Diablo IV not as a child process of the battle.net client? 

**Sunshine Version**: `v2024.914.221909`
**OS Version**: `Windows 11 Home 23H2`

1. The wrapper script appears to be installed correctly in Sunshine and working.
2. Log seems to indicate it is detecting the exit from the game process okay: 
```
**********************
Windows PowerShell transcript start
Start time: 20240917100235
Username: coloso\Jai
RunAs User: coloso\Jai
Configuration Name: 
Machine: COLOSO (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -executionpolicy bypass -windowstyle hidden -file D:\git\PlayNiteWatcher\PlayniteWatcher.ps1 19c68cf0-b41d-4336-93d0-86730be9508b
Process ID: 16104
PSVersion: 5.1.22621.4111
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4111
BuildVersion: 10.0.22621.4111
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is D:\git\PlayNiteWatcher\log.txt
2      PlayniteWatc... BackgroundJob   Running       True            localhost            ...
4      Playnite-Wat... BackgroundJob   Running       True            localhost            ...
Received GamePath: C:\Program Files (x86)\Diablo IV
Waiting for named pipe to recieve kill command
Terminating pipe...
Terminating...
**********************
Windows PowerShell transcript end
End time: 20240917102306
**********************
```
3. When one properly exists out of Diablo IV from the main menu, it simply exits to the battle.net launcher
4. When the Diablo IV process exists one can see the powershell background jobs clear out of task manager

## Workaround / Fix?
Unchecking **Continue streaming until all app processes exit** in the Sunshine Application properties for the game causes the session to terminate.

However, it does seem to **exit with -1** which the moonlight client interprets as an error.

Given the way the wrapper script works, perhaps it would be worthwhile to uncheck this option when the installer is writing to the JSON file?

**Comment by strazto** [comment]
Per https://github.com/Nonary/PlayNiteWatcher?tab=readme-ov-file#session-not-terminating-when-closing-a-game

> If the script doesn’t terminate the session when you close a game, it may be due to the script being saved in a location that requires administrator rights. This script does not run in administrator mode. To resolve this:
> *   Adjust the folder's file permissions to allow write access for users.

Personally, I had the script saved in a non-elevated folder `C:\Users\cstra\Documents\projects\PlayNiteWatcher` (I'd cloned the repo).

But what seemed to work for me was 
![image](https://github.com/user-attachments/assets/a1995cae-1c68-425d-9763-cf47576b5990) unchecking read only here 

Also, in playnite, my app (emulated CEMU game) had been configured to have multiple launch options, and at each launch, withing playnite I'd had to pick which ROM to target, one was base game and one was DLC (i think). 

I removed one of the options, but I doubt this made the difference.
