### ISSUE TITLE
Sunshine becomes offline to Moonlight clients after launching and quitting a game via shortcut once

### ISSUE THREAD

**Issue by MichaelMKenny** [Nonary/PlayNiteWatcher#3]
As the title says, Sunshine shows as offline after quitting a game launched from one of the added Sunshine app shortcuts. This stops a second game launch from working, as the clients aren't able to connect to Sunshine. If you wait many tens of seconds the clients will see Sunshine as online again.

I've been able to mitigate this issue by commenting out this line:
https://github.com/Nonary/PlayNiteWatcher/blob/b0f4a14265a5760101c043126eb1a7d188fbb8a8/PlayniteWatcher-EndScript.ps1#L49

**Comment by Nonary** [comment]
I have not observed this behavior, can you upload the log file for both Sunshine and the script?

**Comment by MichaelMKenny** [comment]
Here are both the logs. This is me starting up Sunshine cold, then launching Spider-Man via the Sunshine shortcut, quitting Spider-Man, then launching Spider-Man again (but the Moonlight launch hanging because it can't contact Sunshine), Seeing Moonlight say the host is offline, and then waiting quite a while for Moonlight to say the server is back online.

[log.txt](https://github.com/Nonary/PlayNiteWatcher/files/11641728/log.txt)
[sunshine.log](https://github.com/Nonary/PlayNiteWatcher/files/11641729/sunshine.log)

**Comment by Nonary** [comment]
Nothing is showing up as a red flag but I did fix a bug with spaces in the game paths, can you pull latest source code and see if that fixes anything

**Comment by Nonary** [comment]
Resolved with the following commits

d41b2cf4055387fa498654925976ef9e69f1ef44
de8552c7db4519168cde3699806ec84afb47e57f
