### ISSUE TITLE
Remove need for sunshine DEBUG logging

### ISSUE THREAD

**Issue by guaycuru** [Nonary/PlayNiteWatcher#5]
Now that Sunshine v0.21 has been released with support for detecting what previously was only available in the logs, could we use that and allow restoring the log level back to the default, like was done for https://github.com/Nonary/AutoHDRSwitch and https://github.com/Nonary/ResolutionAutomation ?

**Comment by Nonary** [comment]
Yes you are correct it shouldn't need debug mode anymore, I'll double check and update the read me files sometime later today

**Comment by Nonary** [comment]
Readme.md has been updated

**Comment by guaycuru** [comment]
Thank you!
