### ISSUE TITLE
[ Feature ] Ability to Configure Paths

### ISSUE THREAD

**Issue by nikuscs** [Nonary/PlayNiteWatcher#6]
Thanks for the Plugin/Tool!

Its possible to specify the Sunshine and Playnite paths beforehand instead having to deal with the "error" everytime? Thanks in advance.

**Comment by Nonary** [comment]
Which errors do you mean?

**Comment by Nonary** [comment]
Implemented in latest release https://github.com/Nonary/PlayNiteWatcher/releases/tag/1.1.0
